apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-api-weather-deployment
  labels:
    app: my-api-weather
spec:
  replicas: 2
  minReadySeconds: 10
  selector:
    matchLabels:
      app: my-api-weather
  template:
    metadata:
      labels:
        app: my-api-weather
    spec:
      containers: 
        - name: my-api-weather
          image: danielparal/apiweather:latest
          ports:
          - containerPort: 80
          resources:
            limits:
              memory: "128Mi"
              cpu: "200m"