apiVersion: v1
kind: Service
metadata:
  name: myapiweather-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: my-api-weather
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80