apiVersion: v1
kind: Service
metadata:
  name: my-bffgateway-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: my-bffgateway
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80