apiVersion: v1
kind: Pod
metadata:
  name: my-api-weather
spec:
  containers:
  - name: my-api-weather
    image: danielparal/apiweather:latest
    livenessProbe:
      httpGet:
        path: /health
        port: 80
      initialDelaySeconds: 15
      timeoutSeconds: 2
      periodSeconds: 5
      failureThreshold: 1